# Generated by Django 6.0.5 on 2026-05-19 17:47

import django.db.models.deletion
import django.utils.timezone
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50, unique=True, verbose_name='Class / Grade')),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monthly Fee (RS)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('admin_username', models.CharField(default='admin_pending', help_text='Custom Superuser login username for this school instance', max_length=150)),
                ('admin_password', models.CharField(default='AxisFallback123!', help_text='Custom Superuser login password', max_length=128)),
                ('school_logo', models.FileField(blank=True, help_text='Upload a school emblem or logo for the portal sidebar.', null=True, upload_to='school_logos/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Student Name')),
                ('father_name', models.CharField(max_length=150, verbose_name='Father Name')),
                ('father_cnic', models.CharField(help_text='Format: 35202-XXXXXXX-X', max_length=15, verbose_name='Father CNIC')),
                ('parent_mobile', models.CharField(max_length=15, verbose_name='Parent Mobile Number')),
                ('grade', models.CharField(max_length=50, verbose_name='Class')),
                ('section', models.CharField(max_length=50, verbose_name='Section')),
                ('admission_date', models.DateField(default=django.utils.timezone.now, verbose_name='Admission Date')),
                ('status', models.CharField(choices=[('active', 'Active Enrolled'), ('suspended', 'Suspended'), ('struck_off', 'Struck Off'), ('graduated', 'Graduated')], default='active', max_length=20, verbose_name='Status')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True, verbose_name='Gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/', verbose_name='Photo (Optional)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes (Optional)')),
                ('roll_number', models.CharField(default='TEMP_TOKEN', max_length=50, verbose_name='Roll Number Token')),
                ('custom_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Assigned Fee (RS)')),
                ('enrolled_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='axis_saas.schoolclient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
