# Generated by Django 6.0.5 on 2026-05-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='b_form_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='B-Form Number'),
        ),
    ]
