# Generated by Django 6.0.5 on 2026-06-02 04:31

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0004_add_tenant_type_and_gym_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymattendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gymsubscription',
            name='cancelled_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gymsubscription',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gymattendance',
            name='check_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gymattendance',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
