# Generated by Django 6.0.5 on 2026-06-03 04:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0005_gymattendance_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymattendance',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='gymcustomer',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='gymattendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
