# Generated by Django 6.0.5 on 2026-06-28 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0010_add_voucher_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feerecord',
            name='extra_charges',
        ),
        migrations.RemoveField(
            model_name='student',
            name='default_extra_charges',
        ),
    ]
