# Generated by Django 6.0.5 on 2026-06-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0011_remove_feerecord_extra_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feerecord',
            name='extra_charges',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='gympayment',
            name='extra_charges',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='gymsubscription',
            name='extra_charges',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='extra_charges',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='default_extra_charges',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
