# Generated by Django 6.0.5 on 2026-06-28 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axis_saas', '0012_add_voucher_fields_final'),
        ('axis_saas', '0012_drop_fee_custom_items'),
    ]

    operations = [
    ]
