# Generated by Django 4.2.16 on 2026-06-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("axis_saas", "0013_merge_20260628_0715"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolfeesettings",
            name="default_extra_charges",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Common charges used for future vouchers",
                null=True,
            ),
        ),
    ]
