# Generated by Django 4.2.16 on 2026-06-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("axis_saas", "0014_schoolfeesettings_default_extra_charges"),
    ]

    operations = [
        migrations.AddField(
            model_name="feerecord",
            name="due_date_offset",
            field=models.PositiveSmallIntegerField(
                default=15, help_text="Days after generation when fee is due"
            ),
        ),
    ]
