# Generated by Django 4.2.16 on 2026-06-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("axis_saas", "0015_feerecord_due_date_offset"),
    ]

    operations = [
        migrations.AddField(
            model_name="feerecord",
            name="late_fee_per_day",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Late fee amount applied per day",
                max_digits=6,
            ),
        ),
    ]
